### ISSUE TITLE
Sqlmap已支持

### ISSUE THREAD

**Issue by CBiu** [HackerYunen/Django-chunked-sqli#1]
Sqlmap现已支持分块传输，见
https://github.com/sqlmapproject/sqlmap/commit/340e250fb1c517ebb401234320d7b6aa1a2190e6

参数--chunked

**Comment by HackerYunen** [comment]
@CBiu 哈哈哈哈，没注意，感谢提交Issue，不过此工具不仅仅能结合sqlmap，还能结合其他无chunk注入的工具，甚至也可以分块post传送xss等，思路很多，用途不限 ：)

**Comment by HackerYunen** [comment]
已更新圈子里的帖子～ 感谢提醒

**Comment by CBiu** [comment]
ok
